http://localhost:3000/cooperado

###
GET http://localhost:3000/cooperado/1

###
GET http://localhost:3000/cooperado/?cpf=92977980040

###
POST http://localhost:3000/cooperado HTTP/1.1
content-type: application/json

{
      "id": 2,
      "cpf": 92977980040,
      "nome": "Marcelo Santos",
      "situacaoCpf": "Regular",
      "contaAplicacaoNumero": 5579323,
      "contaCorrenteNumero": 7784614
}

###
PUT http://localhost:3000/cooperado HTTP/1.1
content-type: application/json

{
       "id": 2,
      "cpf": 92977980040,
      "nome": "Marcelo Santos",
      "situacaoCpf": "Regular",
      "contaAplicacaoNumero": 5579323,
      "contaCorrenteNumero": 7784614
}

###
POST http://localhost:3000/cooperado HTTP/1.1
content-type: application/json

{
      "id": 2,
      "cpf": 92977980040,
      "nome": "Marcelo Santos",
      "situacaoCpf": "Regular",
      "contaAplicacaoNumero": 5579323,
      "contaCorrenteNumero": 7784614
}

###
DELETE http://localhost:3000/cooperado/4
